"""Write data/processed/analysis_digest.md - every key table/number in one place.

This digest is the single source of truth for the written reports: every number quoted in
00-17 must be traceable to this file, a stats CSV, or a source note in /quellen/.
"""
import json
import os

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, "data", "processed")
ST = os.path.join(P, "stats")
OUT = os.path.join(P, "analysis_digest.md")


def fmt(v):
    if isinstance(v, (int, np.integer)):
        return f"{v:,}"
    if isinstance(v, (float, np.floating)):
        if np.isnan(v):
            return ""
        if abs(v) >= 1e6:
            return f"{v/1e6:.2f}M"
        if abs(v) >= 1e4:
            return f"{v/1e3:.0f}K"
        if abs(v) >= 100:
            return f"{v:,.0f}"
        return f"{v:.3g}"
    return str(v)


def md(df, cols=None, n=None):
    if df is None or df.empty:
        return "_(no data)_\n"
    d = df[cols] if cols else df
    if n:
        d = d.head(n)
    head = "| " + " | ".join(str(c) for c in d.columns) + " |\n|" + "---|" * len(d.columns) + "\n"
    body = "".join("| " + " | ".join(fmt(v) for v in row) + " |\n" for row in d.itertuples(index=False))
    return head + body


def seg(name):
    p = os.path.join(ST, f"seg_{name}.csv")
    if not os.path.exists(p):
        return None
    d = pd.read_csv(p)
    return d.rename(columns={d.columns[0]: name})


SEGCOLS = ["n", "median_views", "p90_views", "median_adj_factor", "n_adj", "share_beats_expectation_2x", "median_topic_index", "share_top_quartile_on_topic_page", "median_vpf", "n_vpf",
           "share_viral_5x", "median_likes_per_view", "median_comments_per_view", "low_confidence"]


def main():
    s = json.load(open(os.path.join(ST, "summary.json")))
    df = pd.read_pickle(os.path.join(P, "reels_master.pkl"))
    L = ["# Analysis digest (auto-generated by scripts/digest.py)\n",
         "All numbers derived from public data collected 2026-09-25. Views = public Instagram topic-page counts (rounded as displayed). "
         "topic_index = views ÷ median views of the same topic page (1.0 = typical). vpf = views ÷ followers (followers at fetch). "
         "adj_factor = views relative to expectation for the account's follower count on the same topic page (within-topic regression of log views on log followers; 1.0 = as expected, 2.0 = twice). Segments with n<15 are low confidence.\n",
         "## 1. Dataset\n", "```\n" + json.dumps({k: v for k, v in s.items() if k not in ("kruskal_tests", "within_account")}, indent=1, default=str) + "\n```\n"]
    L.append("### Kruskal-Wallis tests (segments with n>=15): topic_index and size/topic-adjusted residual\n```\n" + json.dumps(s.get("kruskal_tests", {}), indent=1) + "\n```\n")

    kc = os.path.join(ST, "key_contrasts.csv")
    if os.path.exists(kc):
        L.append("### Key contrasts (median ratio A/B, 95% bootstrap CI, Mann-Whitney p)\n" + md(pd.read_csv(kc)))
    # topics
    t = pd.read_csv(os.path.join(ST, "topics.csv"))
    L.append("## 2. Topic pages\n### Top 40 by median views\n")
    tc = ["topic", "group", "n", "median_views", "p90_views", "max_views", "reels_on_topic", "median_views_per_1k_reels", "share_ai_generated", "share_theme_pages", "median_vpf"]
    tc = [c for c in tc if c in t]
    L.append(md(t.sort_values("median_views", ascending=False), tc, 40))
    L.append("### Bottom 20 by median views\n" + md(t.sort_values("median_views"), tc, 20))
    L.append("### Highest views per supply (median views per 1k reels on topic; small reel counts = narrow search phrase)\n" + md(t.dropna(subset=["median_views_per_1k_reels"]).sort_values("median_views_per_1k_reels", ascending=False), tc, 30))
    g = t.groupby("group").agg(n_topics=("topic", "count"), median_of_median_views=("median_views", "median"),
                               max_views=("max_views", "max"), median_reels_on_topic=("reels_on_topic", "median"),
                               mean_share_ai=("share_ai_generated", "mean") if "share_ai_generated" in t else ("n", "count")).reset_index()
    L.append("### Topic groups\n" + md(g.sort_values("median_of_median_views", ascending=False)))
    fp = os.path.join(ST, "freshness_by_group.csv")
    if os.path.exists(fp):
        L.append("### Freshness by topic group (share of top-page reels posted in last 180 days; recent reels' median adj_factor & AI share)\n" + md(pd.read_csv(fp)))
    L.append("### Reel-level by topic group (a reel may be in several groups)\n" + md(seg("topic_groups"), ["topic_groups"] + SEGCOLS))

    order = [("style_primary", "Style"), ("room_primary", "Room"), ("building_type", "Building type"), ("landscape", "Landscape/setting"),
             ("realism", "Realism (fantasy vs realistic)"), ("production", "Production (AI vs real)"), ("shoppability", "Shoppability"),
             ("palette_temp", "Color temperature"), ("brightness", "Brightness"), ("lighting", "Lighting"), ("materials", "Materials (multi)"),
             ("dominant_colors", "Dominant colors (multi)"), ("ambience_fx", "Ambience FX (multi)"), ("cover_hooks", "Visual elements in cover (multi)"),
             ("view_through_window", "Notable view through window"), ("people_present", "People visible"),
             ("caption_hook_category", "Caption hook category"), ("cta_type", "CTA type"), ("caption_len_bucket", "Caption length"),
             ("hashtag_bucket", "Hashtag count"), ("caption_has_question", "Caption has question"), ("caption_link_hint", "Caption link/shop hint"),
             ("caption_comment_cta", "Caption comment CTA"), ("ai_disclosed", "AI disclosed"), ("account_kind_hint", "Account type"),
             ("follower_bucket", "Account size"), ("language", "Caption language"), ("location_any", "Location"), ("post_year", "Post year"),
             ("post_weekday", "Post weekday (UTC)"), ("post_hour_utc", "Post hour (UTC)"), ("visual_quality", "Visual quality"), ("media_type", "Media type")]
    L.append("## 3. Segment tables (sorted by median topic_index)\n")
    for k, title in order:
        d = seg(k)
        if d is None:
            continue
        L.append(f"### {title}\n" + md(d, [k] + [c for c in SEGCOLS if c in d]))
    th = os.path.join(ST, "themes.csv")
    if os.path.exists(th):
        L.append("## 4. Themes (Part 16)\n" + md(pd.read_csv(th)))

    # realism x shoppability & comments
    if "realism" in df:
        d = df[df["views"].notna() & df["realism"].notna()]
        ct = pd.crosstab(d["realism"], d["shoppability"], normalize="index").round(3)
        L.append("## 5. Fantasy vs. realistic\n### Shoppability share by realism (row %)\n" + md(ct.reset_index()))
        agg = d.groupby("realism").agg(n=("shortcode", "count"), median_views=("views", "median"), median_topic_index=("topic_index", "median"), median_adj_factor=("adj_factor", "median"),
                                       median_vpf=("vpf", "median"), share_viral_5x=("vpf", lambda x: (x >= 5).sum() / max(1, x.count())),
                                       median_comments_per_view=("comments_per_view", "median"), median_likes_per_view=("likes_per_view", "median"),
                                       median_comments_per_like=("comments_per_like", "median")).reset_index()
        L.append("### Performance by realism\n" + md(agg))
        agg2 = d.groupby(["realism", "production"]).agg(n=("shortcode", "count"), median_views=("views", "median"), median_topic_index=("topic_index", "median"), median_adj_factor=("adj_factor", "median")).reset_index()
        L.append("### Realism x production\n" + md(agg2[agg2["n"] >= 5]))
        # AI pages vs rest on the same topic pages
        pr = d.groupby("production").agg(n=("shortcode", "count"), median_views=("views", "median"), median_topic_index=("topic_index", "median"), median_adj_factor=("adj_factor", "median"),
                                          median_vpf=("vpf", "median"), share_viral_5x=("vpf", lambda x: (x >= 5).sum() / max(1, x.count())),
                                          median_comments_per_view=("comments_per_view", "median")).reset_index()
        L.append("### Production mode\n" + md(pr))

    # tiers
    L.append("## 6. Virality tiers (vpf)\n```\n" + json.dumps(s.get("tier_counts"), indent=1) + "\n```\n")
    tf = os.path.join(ST, "tier_feature_shares.json")
    if os.path.exists(tf):
        j = json.load(open(tf))
        for k in ["realism", "production", "account_kind_hint", "follower_bucket", "room_primary", "style_primary", "caption_hook_category"]:
            if k in j:
                L.append(f"### {k} share by tier (column %)\n" + md(pd.DataFrame(j[k]).fillna(0).reset_index().rename(columns={"index": k})))
    # within account
    L.append("## 7. Within-account: top 10% vs bottom 50% (same account, views on topic pages)\n```\n" + json.dumps(s.get("within_account"), indent=1, default=str) + "\n```\n")
    wf = os.path.join(ST, "within_account_feature_shares.json")
    if os.path.exists(wf):
        j = json.load(open(wf))
        for k, v in j.items():
            dd = pd.DataFrame(v).fillna(0)
            if {"top10", "bottom50"} <= set(dd.columns):
                dd["diff_top_minus_bottom"] = dd["top10"] - dd["bottom50"]
                dd = dd.sort_values("diff_top_minus_bottom", ascending=False)
            L.append(f"### {k}\n" + md(dd.reset_index().rename(columns={"index": k})))
    # accounts
    a = pd.read_csv(os.path.join(P, "accounts_metrics.csv"))
    ac = ["handle", "followers", "n_reels_sample", "median_views", "max_views", "median_vpf", "max_vpf", "median_topic_index", "median_adj_factor", "account_kind", "production_mode", "share_ai_generated", "style_mode", "first_post_seen"]
    ac = [c for c in ac if c in a]
    L.append("## 8. Accounts\n### Outperformers: median vpf, >=2 reels in sample, >=1K followers\n" + md(a[(a.n_reels_sample >= 2) & (a.followers >= 1000)].sort_values("median_vpf", ascending=False), ac, 40))
    L.append("### Largest accounts in sample\n" + md(a.sort_values("followers", ascending=False), ac, 30))
    L.append("### Most reels on topic pages (breadth)\n" + md(a.sort_values("n_reels_sample", ascending=False), ac, 30))
    if "account_kind" in a:
        k = a.groupby("account_kind").agg(n=("handle", "count"), median_followers=("followers", "median"), median_vpf=("median_vpf", "median")).reset_index()
        L.append("### Account kinds (coded)\n" + md(k.sort_values("n", ascending=False)))
    # top reels list for hook analysis
    cols = ["handle", "views", "vpf", "topic_index", "adj_factor", "topics", "room_primary", "style_primary", "realism", "production", "cover_text", "caption_first_line", "caption_hook_category", "cta_type"]
    cols = [c for c in cols if c in df]
    L.append("## 9. Top 80 reels by adj_factor (beat size expectation most; for hooks / visual patterns)\n" + md(df[df["adj_factor"].notna()].sort_values("adj_factor", ascending=False), cols, 80))
    L.append("## 9b. Bottom 40 reels by adj_factor (coded, for contrast)\n" + md(df[df["adj_factor"].notna() & df.get("visual_status", pd.Series(index=df.index)).eq("ok")].sort_values("adj_factor"), cols, 40))
    L.append("## 10. Top 40 reels by views/follower\n" + md(df[df["vpf"].notna()].sort_values("vpf", ascending=False), cols, 40))
    if "cover_text" in df:
        ct = df[df["cover_text"].notna() & (df["cover_text"].astype(str).str.len() > 2)]
        L.append(f"## 11. Reels with on-cover text overlays: n={len(ct)} of {df['visual_status'].eq('ok').sum()} coded\n" + md(ct.sort_values("topic_index", ascending=False), cols, 60))
    # youtube
    for f, title in [("yt_duration_buckets", "YouTube Shorts proxy: duration buckets"), ("yt_visual_change", "YouTube Shorts proxy: visual change"), ("yt_title_hooks", "YouTube Shorts proxy: title hooks")]:
        p = os.path.join(ST, f + ".csv")
        if os.path.exists(p):
            L.append(f"## {title}\n" + md(pd.read_csv(p)))
    p = os.path.join(P, "youtube_shorts_details.csv")
    if os.path.exists(p):
        y = pd.read_csv(p)
        y["published"] = pd.to_datetime(y["published"], errors="coerce")
        rows = []
        for ch, gg in y.groupby("channel"):
            gg = gg.sort_values("published")
            rows.append({"channel": ch, "n": len(gg), "median_duration_s": gg["duration_sec"].median(), "max_views": gg["views"].max(),
                         "median_views_oldest_half": gg.head(len(gg) // 2)["views"].median(), "median_views_newest_half": gg.tail(len(gg) - len(gg) // 2)["views"].median(),
                         "newest_published": str(gg["published"].max())[:10]})
        L.append("### YouTube channels: older hits vs newest uploads (sample = top-10 popular + 10 newest; age-confounded)\n" + md(pd.DataFrame(rows)))
    p = os.path.join(P, "reels_video_coded.csv")
    if os.path.exists(p):
        L.append("## NexLev video-watched reels (n small; quota 15/day)\n" + md(pd.read_csv(p), ["shortcode", "length_sec", "n_scenes", "room_primary", "style_primary", "camera_motion", "format", "first_frame", "onscreen_text", "audio_type", "music_genre", "production"]))
    p = os.path.join(ST, "reliability.csv")
    if os.path.exists(p):
        L.append("## Coding reliability (independent re-coding)\n" + md(pd.read_csv(p)))
    open(OUT, "w").write("\n".join(L))
    print("digest written:", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    main()
