export const meta = {
  name: 'write-playbook-docs',
  description: 'Write playbook documents from the analysis digest + research notes, then adversarially fact-check and fix each one',
  phases: [{ title: 'Write' }, { title: 'Verify' }],
}
const R = '/home/user/Test-Pr-fung-/instagram-interior-research'
const CTX = `You are a senior social-media growth analyst & content strategist writing part of a data-based Instagram playbook.
Project folder: ${R}. Write in GERMAN (the owner is German). Hooks, captions, prompt examples, content titles and on-screen texts are in ENGLISH (the account is international).
MANDATORY INPUTS — read before writing:
- ${R}/data/processed/strategy_brief.md  (binding decisions & story; stay consistent with it; you may add nuance if the data supports it)
- ${R}/data/processed/analysis_digest.md (all key tables; THE source of numbers; ~160 KB — read the sections relevant to your task fully)
- ${R}/data/processed/stats/*.csv (segment tables incl. median_adj_factor = views vs. expectation for account size on same topic page; median_topic_index; share_viral_5x; comments/view) and ${R}/data/processed/stats/summary.json
- Research notes in ${R}/quellen/q01..q09*.md (only those that exist; cite them with relative links like [q02](quellen/q02_furniture_affiliate_commerce.md) and keep their status tags)
- Charts in ${R}/charts/*.png (embed relevant ones with relative markdown image links, e.g. ![](charts/index_by_style.png); list files with ls first; the adj-based charts are named adj_by_*.png if present)
RULES:
- Every number must be traceable to the digest / a stats CSV / a quellen note / a data CSV. Never invent numbers, accounts, quotes or reel URLs. If data is missing write UNKNOWN. Tag important claims with VERIFIED / ESTIMATED / THIRD-PARTY ESTIMATE / UNKNOWN where appropriate (views & followers from public pages = VERIFIED (rounded); AI-assisted codes = ESTIMATED; YouTube = PROXY).
- Always give n next to segment results; flag n<15 as low confidence; say when a difference is not statistically significant (see Kruskal tests in digest). Never claim causality from correlation; phrase as hypotheses to test.
- Explain the selection bias (topic pages show top reels) where it matters.
- Do NOT copy competitors' creatives: when you show examples of observed hooks/captions, label them as observed examples (short excerpt + handle) and derive the PRINCIPLE; all new hooks/ideas must be original wording.
- Be concrete and practical: tables, checklists, decision rules. No filler, no generic marketing advice without data. Reference the user's Part numbers (e.g. "Teil 17") in headings so they can find each requirement.
- Write the file(s) with the Write tool at the exact path(s) given. Markdown must render on GitHub.`

const TASKS = {
  market: { files: ['01_market_analysis.md'], prompt: `Write ${R}/01_market_analysis.md = TEIL 1 (Ist die Nische attraktiv?). Answer all 10 questions explicitly (Audience-Größe, Konkurrenz-Stärke, Anzahl großer Accounts, Schwierigkeit organischen Wachstums, übersättigte Unterkategorien, wachsende Unterkategorien, AI-Eignung, Kaufabsicht, Möbel-Affiliate-Eignung, Sponsoren-Interesse) for the sub-niches Interior Design, Luxury Interiors, Luxury Homes, Architecture, Future Architecture, AI Architecture, AI Interior Design, Dream Homes, Mansions, Luxury Bedrooms/Living Rooms/Kitchens. Use: topic table (reels_on_topic supply proxy, median/p90/max views, share_ai_generated, share_theme_pages), topic groups, freshness (share of top-page reels from last 180 days — compute from ${R}/04_reel_database.csv columns age_days + topics if needed, via python), AI share by post year, account size effect, large accounts from ${R}/02_competitor_database.csv (count accounts >1M, 500K-1M, 100-500K, <100K), decay evidence (q06, youtube digest section), platform rules (q01), trends/demand (q04), cross-platform (q08), benchmarks (q09 if present), sponsors (q03), affiliate (q02). Include a scoring table per sub-niche (Reichweite, Konkurrenz, AI-Eignung, Kaufabsicht, Affiliate, Sponsoren; 1-5 with justification) and a clear, critical verdict ("Nische attraktiv? unter welchen Bedingungen / wo nicht"). Embed charts topics_demand_vs_supply.png and relevant index/adj charts.` },
  competitors: { files: ['03_competitor_analysis.md'], prompt: `Write ${R}/03_competitor_analysis.md = TEIL 2 (Überblick über 50+ Accounts nach Gruppen A–H), TEIL 3 (Shortlist der 20 interessantesten Accounts, NICHT nach Followern), TEIL 4 (Analyse der Top-Accounts und ihrer Reels, soweit öffentlich), TEIL 20 teilweise (Monetarisierung pro Top-Account). Inputs: ${R}/02_competitor_database.csv (all accounts, groups, statuses), ${R}/data/processed/shortlist_scores.csv (rank, score components, outperformer flag; explain the scoring method from ${R}/scripts/shortlist.py docstring), deep profiles ${R}/data/raw/accounts/profile_*.json (bio, links, offers, brand deals, content_mode, niche_focus, cta_pattern), per-reel data in ${R}/04_reel_database.csv (filter by handle with python/pandas to describe each top account's reels: views, vpf, adj_factor, styles, rooms, realism, hooks, cover texts), q05/q06 notes. Content: (a) group overview table A–H with counts and examples incl. follower tiers (<100K with millions of views, 100–500K, 500K–1M, >1M, new fast growers = earliest known post recent + high followers); (b) 'Outperformance Accounts' table: views/followers (median & max) with n reels, e.g. '50K Follower + 1M Views = 20×'; (c) Top-20 shortlist table with score breakdown and 3–5 sentence analysis each: what they do, format, visual signature, hook style, AI/real, monetization (VERIFIED/UNKNOWN), what we can LEARN (principle) and what NOT to copy; (d) cross-account patterns; (e) limitations (WebSearch budget exhausted → some bios UNKNOWN; last-20-reels per account not accessible without login → we used topic-page samples; posting frequency = upper bound).` },
  viral: { files: ['05_viral_patterns.md'], prompt: `Write ${R}/05_viral_patterns.md = TEIL 7 (Video-Aufbau: Länge, Szenen, Geschwindigkeit, Kamerafahrt – state honestly what is measurable: NexLev 7 reels, YouTube proxy visual-change & duration, cover coding), TEIL 8 (erste 1–2 Sekunden / visuelle Hooks: use cover-frame coding cover_hooks + first_frame of NexLev reels; state that the cover is a proxy for the first impression), TEIL 12 (Videolänge vs Performance with the required buckets 0–5/6–8/9–12/13–20/21–30/30+ from the YouTube proxy: median views, mean views, views relative to channel median, 'Viralitätsquote' = share ≥2× channel median; clearly mark as PROXY and list confounders), TEIL 13 (Postingfrequenz: competitor posting_freq upper bounds from ${R}/02_competitor_database.csv; bucket accounts into ~1/2/3/4+ per day by upper bound; relate to follower size/outperformance only as correlation; also posting hour/weekday results = no significant effect), TEIL 14 (Viralitätsstufen NORMAL/GOOD/VERY GOOD/VIRAL/EXTREME OUTLIER with counts and what distinguishes EXTREME OUTLIERS — use tier_feature_shares from digest; add absolute thresholds for small accounts), TEIL 15 (Gewinner vs Verlierer innerhalb desselben Accounts: digest section 7 — top 10% vs bottom 50%, n accounts/reels, feature differences; plus global top vs bottom by adj_factor digest sections 9/9b). Include a synthesized 'Viral-Formel' as testable hypotheses with the evidence strength (stark/mittel/schwach). Embed charts: views_by_length_yt_proxy.png, views_by_camera_yt_proxy.png, index/adj charts for visual hooks, vpf_by_account.png.` },
  styles: { files: ['06_visual_styles.md'], prompt: `Write ${R}/06_visual_styles.md = TEIL 5 (Szenen/Räume & Architektur-/Interior-Stile), TEIL 6 (Farben & Materialien incl. the example question warm wood/stone vs sterile white — test with data: palette_temp, brightness, materials, dominant_colors), TEIL 16 (Themenperformance rankings: Bedroom, Living Room, Kitchen, Bathroom, Villa, Pool, Outdoor, Penthouse, Hotel, Mansion, Mountain/Ocean/Desert Home, Dubai, Monaco, Bali, Maldives, Switzerland, New York, Tokyo + other relevant — median views, top 10% (p90) views, views/follower, adj_factor, n; use themes.csv, seg_location_any.csv etc.), TEIL 17 (Welche Stile funktionieren: views, comments/view, likely saves (proxy: likes/view & shoppability; saves are not public → say so), Möbelpotenzial), TEIL 18 (Fantasy vs Aspirational-realistic — test the hypothesis carefully with realism × production, shoppability, comments/view; conclusion for business model). Include the AI-only breakdowns (run python on ${R}/04_reel_database.csv filtered production=='ai_generated' for style/room/realism medians of adj_factor with n). Embed charts views_by_style/index_by_style/adj charts, views_by_room, views_by_theme, views_by_location, views_by_realism, views_by_production, views_by_palette, views_by_material, views_by_lighting.` },
  hooks: { files: ['07_hooks.md'], prompt: `Write ${R}/07_hooks.md = TEIL 8/9 analysis (visual hooks + text hooks: categorize observed caption first lines and cover texts into Curiosity, POV, Aspirational, Choice, Question, Status, Money, Location, Fantasy, Contrarian (+ Instructional/Descriptive/Promotional) with performance per category (n, median views, adj_factor, comments/view) overall and within AI; YouTube title-hook proxy; the psychological principle behind each), TEIL 25 (Hook Library: EXACTLY 50 ORIGINAL English hook concepts, categorized POV / Question / Choice / Curiosity / Dream / Location / Price / Status / Story — for each: pattern template like "POV: [aspirational situation]" + 1–2 original example lines + which pillar it fits + data rationale + risk note e.g. fictional price must be labeled as concept), TEIL 26 (Visual Hook Library: at least 30 ORIGINAL visual hook concepts for the first 1–2 seconds, abstracted principles e.g. 'camera starts inches above water surface of an infinity pool then rises to reveal a cantilevered house', each with pillar, camera move, duration of hook shot, why (data link), and generation notes). Do NOT reuse any observed caption verbatim; the digest lists observed ones (sections 9–11) — use them only as labeled observed examples. Favour what the data supports: choice mechanics, curiosity/price framing, human scale, night light, unusual architecture reveal; avoid what underperforms (location-only, instructional, text-heavy covers, split-screen before/after).` },
  pillars_style: { files: ['08_content_pillars.md', '11_brand_style_guide.md'], prompt: `Write TWO files.
(1) ${R}/08_content_pillars.md = TEIL 24: 5–8 Content Pillars — start from the strategy brief pillars (P1–P5) and only keep/add pillars the data supports. For each: Ziel, typische Views (range from comparable segments in the digest, clearly as benchmark of top-page reels, not a promise), Share-/Save-/Follow-/Affiliate-Potenzial (rated 1–5 with data rationale; saves & follows are not public → proxies), example series names, reel formats, frequency share in the 30-day test, KPIs to judge it, kill criteria.
(2) ${R}/11_brand_style_guide.md = TEIL 23: an original, recognizable style system derived from success PRINCIPLES (not copying): Farben (hex palette with roles), Licht, Materialien, Architektur-Vokabular, Möbel (incl. 'buyable hero pieces' rule for commerce pillars), Perspektiven, Kamerafahrten, Geschwindigkeit, Musik/Audio (Instagram licensing constraints for business accounts from q01/q07 if present; audio is UNKNOWN in our data → testing), Text (on-screen text rules), Schrift (font suggestions + sizes/safe zones for 9:16), Video-Länge, Hook-Stil, Übergänge, wiedererkennbare Elemente (series numbering, signature ending, color contrast, human scale figure), AI-Kennzeichnung im Markenauftritt, Do/Don't list with data references, and 5 example prompt blocks for image/video generation (English) that encode the style. Goal: after a few weeks viewers recognize 'this is probably from this account'.` },
  monetization: { files: ['09_monetization.md'], prompt: `Write ${R}/09_monetization.md = TEIL 19 (Konkurrenz beim Möbel-Affiliate: which accounts link furniture / shop-the-look / Amazon storefront / LTK / ShopMy / own shops — from deep profiles ${R}/data/raw/accounts/profile_*.json fields link_in_bio.offers, monetization_evidence, brand_deals_seen, and ${R}/02_competitor_database.csv has_* flags; how they integrate commerce without looking like ads — observed patterns e.g. comment-keyword→DM funnels, 'curated collection by DM', finds-style lifestyle creators), TEIL 20 (Monetarisierung der Konkurrenz: Affiliate, Sponsored Posts, Interior/Furniture Brands, Real Estate, Courses, Digital Products, Services, Newsletter, Apps/Software — table for top accounts with VERIFIED/UNKNOWN; no income estimates unless THIRD-PARTY ESTIMATE from quellen), plus our own monetization roadmap by phase (0–10K, 10–50K, 50–200K, 200K+ followers) ranked by evidence: KI-Tool-Sponsoring/Affiliate, B2B visualization services, digital products, furniture affiliate via choice/transformation formats (with the 'Impossible places, possible furniture' test), real-estate/developer deals (compliance), newsletters; include program conditions from q02/q03 (commission %, cookie windows, disclosure rules; Amazon boosted-post exclusion), a unit-economics sketch clearly labeled as assumption (e.g. revenue per 1,000 views scenarios) and legal/disclosure requirements.` },
  gaps: { files: ['10_market_gaps.md'], prompt: `Write ${R}/10_market_gaps.md = TEIL 21 (at least 10 micro-niches with high demand + strong views + few specialized accounts; for each: Wettbewerb, potenzielle Reichweite, AI-Eignung, Möbel-Affiliate-Eignung, Sponsoring, Differenzierung, evidence with numbers: topic median views & reels_on_topic supply proxy & freshness & adj_factor & AI share; include both promising and explicitly REJECTED micro-niches with reasons, e.g. AI Tropical Luxury Homes, Future Bedrooms, Luxury Homes in Impossible Locations, AI Landscaping/garden transformations, impossible bathrooms, night penthouses, alpine/Swiss concept homes, underground oases, treehouse/cliff homes, 'pick one' rooms, cozy night retreats (saturation!), AI hotels (weak)) and TEIL 22 (5 account concepts derived from observed market patterns: Name/Positionierung, Content, Visueller Stil, Zielgruppe, Warum könnte es wachsen (data), Monetarisierung, Konkurrenzstärke, Reel-Arten; then a comparison matrix and the recommended concept consistent with the strategy brief). Use the topic demand-vs-supply table (median_views_per_1k_reels; note small reel counts are narrow search phrases), freshness by group, AI-only segment results.` },
  ideas: { files: ['12_100_content_ideas.csv'], prompt: `Create ${R}/12_100_content_ideas.csv = TEIL 27: EXACTLY 100 concrete, ORIGINAL reel ideas (English content fields) as a CSV (UTF-8, comma-separated, properly quoted) with columns: id,titel,content_pillar,hook,visual_hook_first_2s,raum,location,stil,farbschema,kamera,laenge_sek,text_overlay,cta,monetarisierung,warum_laut_daten,test_variable,prioritaet. Distribute across pillars per the strategy brief mix (P1 ~35, P2 ~20, P3 ~20, P4 ~15, P5 ~10). 'warum_laut_daten' must cite a concrete data point from the digest (segment + adj_factor or n) or say 'explorativ'. Respect the style guide principles in the strategy brief (night warm light, human scale, unusual structures, no split-screen covers, ≤5 hashtags not needed here). Prices/locations in hooks must be framed as concepts (never claim a fictional home exists or is for sale). After writing, validate with python (pandas.read_csv) that there are exactly 100 rows and all columns are non-empty; fix until valid.` },
  plan: { files: ['13_testing_matrix.csv', '14_30_day_launch_plan.md'], prompt: `Create TWO files.
(1) ${R}/13_testing_matrix.csv = TEIL 28: a structured experiment design so we learn WHAT causes performance. Columns: test_id,woche,hypothese,variable_getestet,konstant_gehalten,varianten,anzahl_reels,reel_ids_im_plan,primaer_kpi,sekundaer_kpi,entscheidungsregel,datenbasis_der_hypothese. Cover variables HOOK, STYLE, ROOM, LOCATION, VIDEO LENGTH, CAMERA, TEXT, AUDIO, plus REALISM (fantasy vs realistic), HUMAN PRESENCE, LIGHT (night vs day), COVER TEXT (none vs overlay), CTA, 'Impossible places, possible furniture' hybrid. Use one-variable-at-a-time designs (same body, 3 hooks; same hook, 3 styles, etc.) and paired A/B within the same week; at least 25 tests fitting into 90 reels over 30 days (a reel may serve as control in more than one test). Validate with pandas.
(2) ${R}/14_30_day_launch_plan.md = TEIL 29: 3 reels/day = 90 reels; Woche 1 breite Tests, Woche 2 schwache Kategorien eliminieren, Woche 3 Gewinner verdoppeln, Woche 4 Gewinner skalieren; day-by-day table (Tag, Reel 1–3 with pillar/format/test_id), posting times (data shows no significant hour effect → consistent slots + test), production workflow per day, exact KEEP / ITERATE / SCALE / KILL rules with thresholds based on KPIs (views/follower, follows per 1,000 views, shares per 1,000 views, comments per 1,000 views, completion/avg watch time; use relative thresholds vs the account's own rolling median since absolute benchmarks for a new account are unknown; reference ${R}/15_kpi_framework.md if it exists), Trial Reels usage (q01), weekly review ritual using ${R}/scripts/winner_analysis.py and the competitor monitor (${R}/17_competitor_monitor.md). Keep consistent with ${R}/13_testing_matrix.csv.` },
  sources: { files: ['quellen/README.md'], prompt: `Write ${R}/quellen/README.md = TEIL 34 (Quellenqualität): an index of all sources used. (1) Primary data sources of this research with method, date, what is VERIFIED vs ESTIMATED vs UNKNOWN: Instagram public topic pages, public embed pages, shortcode timestamp decoding (explain), CDN cover frames + AI-assisted coding (reliability table from ${R}/data/processed/stats/reliability.csv), NexLev video watcher (15/day cap), NexLev YouTube data (third-party provider), WebSearch/WebFetch research notes. (2) Table of each research note q01..q09 (that exists) with topic, number of sources, main source types, fact-check results (read the '## Faktencheck (automatisiert)' sections if present and summarize CONFIRMED/NOT_CONFIRMED counts). (3) A consolidated list of the most important external URLs (extract markdown links from the q-notes with python; dedupe; group by source type: Meta/Instagram primary, company program pages, analytics platforms, news/industry, blogs/case studies) — at most ~150 links. (4) Source-quality ranking rules applied (1 public Instagram data, 2 Meta primary, 3 analytics platforms, 4 public account data, 5 case studies). (5) Known limitations & biases.` },
}

const VSCHEMA = { type: 'object', properties: { checked_claims: { type: 'integer' }, errors_found: { type: 'integer' }, fixes_applied: { type: 'integer' }, notes: { type: 'string' } }, required: ['checked_claims', 'errors_found', 'fixes_applied'] }

const keys = args.keys
const res = await pipeline(
  keys,
  k => agent(`${CTX}\n\nTASK:\n${TASKS[k].prompt}`, { label: 'write:' + k, phase: 'Write' }).then(() => k),
  k => agent(`You are an adversarial fact-checker for the file(s) ${TASKS[k].files.map(f => R + '/' + f).join(', ')} of an Instagram research playbook (German). Your job: find and FIX errors. Sources of truth: ${R}/data/processed/analysis_digest.md, ${R}/data/processed/stats/*.csv, ${R}/data/processed/stats/summary.json, ${R}/02_competitor_database.csv, ${R}/04_reel_database.csv, ${R}/data/processed/shortlist_scores.csv, ${R}/data/raw/accounts/profile_*.json, ${R}/quellen/*.md, ${R}/data/processed/strategy_brief.md.
Check: (1) every number/percentage/n/account figure against the sources (use python/grep; allow rounding) — fix wrong numbers or remove unsupported ones; (2) claims of causality or significance that the data does not support (Kruskal tests in summary.json; n<15) — soften them; (3) invented accounts, URLs, quotes; (4) consistency with strategy_brief.md; (5) for CSV files: row counts and required columns (validate with pandas) and that hooks/ideas are original (no verbatim copy of observed captions: compare with caption_first_line/cover_text columns of 04_reel_database.csv using difflib, ratio>0.85 = rewrite); (6) broken relative links to charts/files (check files exist). Edit the file(s) in place with Edit/Write. Keep the document's structure and language. Return counts.`, { label: 'verify:' + k, phase: 'Verify', schema: VSCHEMA }).then(v => ({ key: k, verify: v })),
)
return res
